# Generated by Django 2.2.7 on 2019-11-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=500)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('nacio', models.CharField(max_length=400)),
                ('papa', models.CharField(max_length=500)),
                ('mama', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero')], default='Soltero', max_length=10)),
                ('ocupacion', models.CharField(max_length=200)),
                ('leer_escribir', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10)),
                ('curp', models.CharField(max_length=500)),
                ('grado_maximo', models.CharField(max_length=500)),
                ('domicilio', models.CharField(max_length=500)),
                ('presidente', models.CharField(max_length=500)),
                ('lugar', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cartillas',
            },
        ),
    ]
