# Generated by Django 2.2.7 on 2019-11-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartilla', '0002_auto_20191121_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartilla',
            name='clase',
            field=models.IntegerField(default=0, verbose_name='CLASE'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='curp',
            field=models.CharField(max_length=500, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='domicilio',
            field=models.CharField(max_length=500, verbose_name='DOMICILIO'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='estado',
            field=models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero')], default='Soltero', max_length=10, verbose_name='ESTADO CIVIL'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='FECHA'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='FECHA DE NACIMIENTO'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='grado_maximo',
            field=models.CharField(max_length=500, verbose_name='GRADO MÁXIMO DE ESTUDIOS'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='leer_escribir',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, verbose_name='¿SABE LEER Y ESCRIBIR?'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='lugar',
            field=models.CharField(max_length=500, verbose_name='LUGAR'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='mama',
            field=models.CharField(max_length=500, verbose_name='Y DE'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='nacio',
            field=models.CharField(max_length=400, verbose_name='NACIÓ EN'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='nombre',
            field=models.CharField(max_length=500, verbose_name='NOMBRE'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='ocupacion',
            field=models.CharField(max_length=200, verbose_name='OCUPACIÓN'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='papa',
            field=models.CharField(max_length=500, verbose_name='HIJO DE'),
        ),
        migrations.AlterField(
            model_name='cartilla',
            name='presidente',
            field=models.CharField(max_length=500, verbose_name='PRESIDENTE'),
        ),
    ]
