# Generated by Django 2.2.7 on 2019-11-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartilla', '0003_auto_20191121_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartilla',
            name='estado',
            field=models.CharField(choices=[('CASADO', 'CASADO'), ('SOLTERO', 'SOLTERO')], default='SOLTERO', max_length=10, verbose_name='ESTADO CIVIL'),
        ),
    ]
