# Generated by Django 2.2.7 on 2019-12-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartilla', '0005_auto_20191122_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartilla',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='FECHA'),
        ),
    ]
